FROM n8nio/n8n:latest

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=${N8N_USER}
ENV N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
ENV N8N_PORT=5678
ENV N8N_WORKFLOW_MANAGEMENT_ACTIVE=true

EXPOSE 5678

CMD ["n8n"]
